#!/usr/bin/env bash
set -euo pipefail

if [[ "$#" -ne 10 ]]; then
  echo "usage: asmory-add <package> <release> <capability> <semantic-fingerprint> <profile> <provider> <variant> <artifact-sha256> <review-state> <safety-state>" >&2
  exit 2
fi

package="$1"
release="$2"
capability="$3"
semantic_fp="$4"
profile="$5"
provider="$6"
variant="$7"
artifact_sha="$8"
review_state="$9"
safety_state="${10}"

[[ "$package" =~ ^[a-z0-9][a-z0-9._-]*$ ]] || {
  echo "add: invalid package name" >&2
  exit 2
}
[[ "$release" =~ ^[0-9A-Za-z][0-9A-Za-z._+-]*$ ]] || {
  echo "add: invalid release" >&2
  exit 2
}
[[ "$artifact_sha" =~ ^[0-9a-f]{64}$ ]] || {
  echo "add: invalid Artifact SHA-256" >&2
  exit 2
}
[[ "$semantic_fp" =~ ^[0-9a-f]{64}$ ]] || {
  echo "add: invalid semantic fingerprint" >&2
  exit 2
}

for value in "$capability" "$profile" "$provider" "$variant" "$review_state" "$safety_state"; do
  [[ "$value" =~ ^[A-Za-z0-9._/@:+-]+$ ]] || {
    echo "add: unsafe resolver metadata value rejected" >&2
    exit 2
  }
done

for cmd in asmory-cache asmory-materialize asmory-state flock; do
  command -v "$cmd" >/dev/null 2>&1 || {
    echo "add: required bootstrap helper unavailable: $cmd" >&2
    exit 10
  }
done

[[ -f asm.toml && -f asm.lock && -d .asmory/deps ]] || {
  echo "add: no initialized Asmory workspace; run 'asmory init' first" >&2
  exit 9
}

exec 9>.asmory/workspace.lock
if ! flock -n 9; then
  echo "add: another Asmory workspace mutation is in progress" >&2
  exit 14
fi

expected_manifest="$(mktemp .asmory/expected-manifest.XXXXXX)"
expected_lock="$(mktemp .asmory/expected-lock.XXXXXX)"
tmp_manifest="$(mktemp .asmory/manifest.XXXXXX)"
tmp_lock="$(mktemp .asmory/lock.XXXXXX)"
backup_manifest="$(mktemp .asmory/manifest-backup.XXXXXX)"
backup_lock="$(mktemp .asmory/lock-backup.XXXXXX)"

published_dep=0
metadata_started=0
committed=0

cleanup() {
  rc=$?
  trap - EXIT INT TERM

  if (( committed == 0 )); then
    if (( metadata_started )); then
      cp -- "$backup_manifest" asm.toml 2>/dev/null || true
      cp -- "$backup_lock" asm.lock 2>/dev/null || true
    fi

    if (( published_dep )); then
      rm -rf -- ".asmory/deps/$package"
    fi
  fi

  rm -f -- \
    "$expected_manifest" "$expected_lock" \
    "$tmp_manifest" "$tmp_lock" \
    "$backup_manifest" "$backup_lock"

  exit "$rc"
}
trap cleanup EXIT INT TERM

cat >"$expected_manifest" <<'EOF'
# Asmory project manifest.
# User intent lives here; exact resolution lives in asm.lock.
schema = 1

[workspace]
resolver_policy = "asmory-v1"

[dependencies]
EOF

cat >"$expected_lock" <<'EOF'
# Generated by Asmory. Do not edit by hand.
# Exact resolved reality will be recorded here.
schema = 1
resolver_policy = "asmory-v1"
dependency_count = 0
EOF

if ! cmp -s asm.toml "$expected_manifest" || ! cmp -s asm.lock "$expected_lock"; then
  echo "add: MVP requires the canonical empty workspace; refusing to rewrite existing dependency state" >&2
  exit 15
fi

if [[ -e ".asmory/deps/$package" || -L ".asmory/deps/$package" ]]; then
  echo "add: dependency destination already exists: .asmory/deps/$package" >&2
  exit 15
fi

for ignored in 'deps/' '.staging/' '.restore/' '.delta/' '.vendor/' 'workspace.lock'; do
  grep -qxF "$ignored" .asmory/.gitignore 2>/dev/null ||
    printf '%s\n' "$ignored" >> .asmory/.gitignore
done

cache_object="$(asmory-cache "$package" "$release" "$artifact_sha" --print-object)"
[[ -f "$cache_object" && ! -L "$cache_object" ]] || {
  echo "add: cache backend did not return a regular object" >&2
  exit 13
}

asmory-materialize \
  "$package" \
  "$artifact_sha" \
  "$cache_object" \
  ".asmory/deps" >/dev/null
published_dep=1

tree_sha="$(asmory-state tree-hash ".asmory/deps/$package")"
[[ "$tree_sha" =~ ^[0-9a-f]{64}$ ]] || {
  echo "add: failed to compute deterministic materialized tree hash" >&2
  exit 18
}

cat >"$tmp_manifest" <<EOF
# Asmory project manifest.
# User intent lives here; exact resolution lives in asm.lock.
schema = 1

[workspace]
resolver_policy = "asmory-v1"

[dependencies]
$package = "*"
EOF

cat >"$tmp_lock" <<EOF
# Generated by Asmory. Do not edit by hand.
# Exact resolved reality is recorded here.
schema = 1
resolver_policy = "asmory-v1"
dependency_count = 1

[[dependency]]
name = "$package"
intent = "*"
release = "$release"
capability = "$capability"
semantic_fingerprint = "$semantic_fp"
profile = "$profile"
provider = "$provider"
variant = "$variant"
artifact_kind = "source"
artifact_sha256 = "$artifact_sha"
tree_hash_schema = "asmory-tree-v1"
materialized_tree_sha256 = "$tree_sha"
review_state = "$review_state"
registry_safety = "$safety_state"
materialized_path = ".asmory/deps/$package"
source_kind = "registry"
EOF

cp -- asm.toml "$backup_manifest"
cp -- asm.lock "$backup_lock"

metadata_started=1
mv -f -- "$tmp_manifest" asm.toml
mv -f -- "$tmp_lock" asm.lock

committed=1
trap - EXIT INT TERM
rm -f -- \
  "$expected_manifest" "$expected_lock" \
  "$backup_manifest" "$backup_lock"

echo "Dependency added"
echo
echo "  package      $package"
echo "  release      $release"
echo "  profile      $profile"
echo "  variant      $variant"
echo "  artifact     $artifact_sha"
echo "  local        .asmory/deps/$package"
echo "  manifest     asm.toml"
echo "  lockfile     asm.lock"
